# MongoDB. Postgres
services:
  mongo:
    image: mongo
    container_name: my-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db
      - ./databases/mongo/init:/docker-entrypoint-initdb.d
  postgres:
      image: postgres:latest
      container_name: my-postgres
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - pgdata:/var/lib/postgresql
        - ./databases/postgres/init:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
volumes:
  mongodata:
  pgdata:
  rabbitmqdata: